---
- name: Charles Playbook
  hosts: localhost
  tasks:
  - name: Create a File with content
    copy:
      dest: "/tmp/lee.txt"
      content:
       Tottenham Hotspurs stadium tonight \n
  #- name: Move file from tmp to home directory
  #  command: mv /tmp/lee.txt /home/clee/lee.txt
    
  #- name: show result in shell
  #  shell: echo "Tottenham" > /home/clee/spurs.txt
  #  register: shell_output

  #- name: Debug shell output
  #  debug: var=shell_output
      
    

 

 
 #  - name: Ping Host
 #    ansible.builtin.ping:
  
 #  - name: Print message
 #    ansible.builtin.debug:
 #      msg: Ansible is working


    
